# Generated by Django 6.0.6 on 2026-07-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_contact_alter_product_desc_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=70)),
                ('address', models.CharField(blank=True, max_length=15)),
                ('city', models.CharField(blank=True, max_length=15)),
                ('stete', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(max_length=100)),
            ],
        ),
    ]
