# Generated by Django 6.0.6 on 2026-07-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='stete',
            new_name='state',
        ),
    ]
