# Generated by Django 6.0.6 on 2026-07-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_orders_items_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='items_json',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
