# Generated by Django 6.0.6 on 2026-08-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_orders_paid_orders_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
