# Generated by Django 6.0.6 on 2026-08-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_orders_payment_status_orders_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
